apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: pipeline-radar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ingestion-service
        image: ghcr.io/hashini-sugandika/pipeline-radar-ingestion:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          value: postgresql://radar:radarpass@postgres:5432/pipelineradar
        - name: REDIS_URL
          value: redis://redis:6379
        - name: GITHUB_WEBHOOK_SECRET
          value: ""
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: pipeline-radar
  labels:
    app: ingestion-service
spec:
  selector:
    app: ingestion-service
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: NodePort
